### ISSUE TITLE
Box and ConvexPolyhedron do not collide ?

### ISSUE THREAD

**Issue by synth2014** [schteppe/cannon.js#175] opened 2015-01-22 18:56 UTC
Here is a sample

http://synth2014.github.io/Age-of-Steam/engg/ConvexPolyhedron.html

Only the corner seems to collide for some reason.

**Comment by recoshet** [comment] 2015-01-22 21:02
ConvexPolyhedron collide with the cube 
http://naviris.ru/3D2/trimesh2.html 
select "convex hull mesh".

But trimesh somehow does not interact with the cube

**Comment by schteppe** [comment] 2015-02-01 13:16
Hmmm... Looks like a very thin box you got there. Don't use thin shapes. Are you building it manually as a ConvexPolyhedron? Why not use a Box?

**Comment by schteppe** [comment] 2015-02-01 13:18
@recoshet no, trimesh/convex collision is not yet implemented. See the collision table in the readme.

**Comment by schteppe** [comment] 2015-02-21 11:32
I believe the issue is fixed with the commit from @oxyflour. Closing.

**Closed by schteppe** 2015-02-21 11:32 UTC
